[toolchain]
package_manager = "yarn"
anchor_version = "0.31.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking = "FK2cxLLF8wDCREL3t1uoijHTw2fmSjJxxM6STijFwPJn"

[programs.devnet]
staking = "ESyQQgk2Z71K72RFGxxUk9RSFLwEx3BJGh4EhVydr8G"

[programs.mainnet]
staking = "FK2cxLLF8wDCREL3t1uoijHTw2fmSjJxxM6STijFwPJn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "node scripts/verify-deployment.js"
verify = "node scripts/verify-deployment.js"
